config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'searches/search'
  end
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update ]
  end
# 顧客用
# URL /users/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 root to: 'public/home#top'
 scope module: :public do
    resources :maps, only: [:index, :show, :new, :create, :destroy] do
     resource :favorites, only: [:create, :destroy]
     resources :post_comments, only: [:create, :destroy]
    end
    get 'home/about'
    get 'searches/search'
    resources :users, only: [:show] do
     get :favorites, on: :collection
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/map.rb
class Map < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :image

  validates :shop_name, presence: true
  validates :body, presence: true
  validates :lat, presence: true
  validates :lng, presence: true
  validates :cooking_genre, presence: true
  validates :peko, presence: true
   
    def favorited_by?(user)
      favorites.exists?(user_id: user.id)
    end
   
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]

  has_many :maps, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :email,  length: { maximum: 30 }


end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
   def after_sign_in_path_for(resource)
    admin_users_path
   end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @maps = @user.maps
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to  admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted, :name, :email)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    maps_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_link_item(name, path)
    class_name = 'channel'
    class_name << ' active' if current_page?(path)

    content_tag :li, class:class_name do
      link_to name, path, class: 'channel_name'
    end
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/admin/users/edit.html.erb
<div class = "col-8  pl-5 pt-5" >
  <%= form_with model: @user, url: admin_user_path, method: :patch, local: true do |f| %>
    <div class="field row">
      <div class = "col-2"><%= f.label :会員ID %></div>
      <div class = "col-5"><%= @user.id %></div>
    </div>
    <div class="field row">
      <div class = "col-2"><%= f.label :氏名 %></div>
      <div class = "col-5">
        <%= f.text_field :name, autofocus: true %>
      </div>
    </div>
    <div class="field row">
      <div class = "col-2"><%= f.label :メールアドレス %></div>
      <div class = "col-5"><%= f.email_field :email %></div>
    </div>
    <div class="field row">
      <div class = "col-2"><%= f.label :ステータス %></div>
      <div class = "col-5">
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted, '有効', value: true %>
        <%= f.radio_button :is_deleted, true %>
        <%= f.label :is_deleted, '退会', value: false %>
      </div>
    </div>
    <div>
      <%= f.submit "変更を保存" %>
    </div>
  <% end %>
</div>
</div>

app/views/admin/users/index.html.erb
<div class = "col-9" >
  <table class="table table-hover table-inverse admin_customers_table">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= link_to admin_user_path(user) do %>
                <%= user.name %>
              <% end %>
          </td>
          <td><%= user.email %></td>
          <td>
            <% if user.is_deleted == false %>
                有効
            <% else %>
                退会
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/show.html.erb
<div class = "col-8 pl-5 pt-3" >
  <h2><%= @user.name %>さんの詳細画面</h2>
    <div class="form-group row">
      <div class="col-2">会員ID</div>
      <div class="col-5"><%= @user.id %></div>
    </div>
    <div class="form-group row">
      <div class="col-2">氏名</div>
      <div class="col-5">
          <%= @user.name %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-2">メールアドレス</div>
      <div class="col-5"><%= @user.email %></div>
    </div>
    <div class="form-group row">
      <div class="col-2">会員ステータス</div>
      <div class="col-5">
          <% if @user.is_deleted == false %>
              有効
          <% else %>
              退会
          <% end %>
      </div>
    </div>
    <div>
      <h5><%= link_to "編集する", edit_admin_user_path %></h5>
    </div>
    <br>
  <h2><%= @user.name %>さんの投稿一覧画面</h2>
      <% @maps.each do |map| %>
    <div class = pt-2>
        <% if map.image.attached? %>
          <%= image_tag map.image, size: "100x80" %>
        <% else %>
          <%= image_tag "no_image.jpg", size: "100x100" %>
        <% end %>
          店名<%= map.shop_name %>
          注文内容<%= map.body %>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Are_you_ready_to_order</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- 文字のフォント変更の読み込み -->
    <link href="https://fonts.googleapis.com/css2?family=Mochiy+Pop+One&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class = "row no-gutters">
      <div class = "col-1">
        <div class="listings">
          <div class="listings_channels">
                <div class = "pecokuro">
                  <p><%= image_tag 'logo-peco2.png', width: "145%", height: "100%" %></p>
                </div>
                  <!--検索機能-->
                  <% if current_page?(maps_path || searches_search_path)%>
                    <div class = "search_peko">
                      <h7>今の腹ペコ度でお店の絞込みできます。</h7>
                      <div class = "form-select">
                        <%= form_with url: searches_search_path, method: :get, local: true do |f| %>
                          <%= f.select :peko, [['ちょいペコ','ちょいペコ'], ['ペコ','ペコ'], ['ペコMAX','ペコMAX']], {prompt: '  --  選択してください  --  '}, class: "select" %>
                           <div class = "submit" ><%= f.submit '検索' %></div>
                        <% end %>
                      </div>
                    </div>
                  <% elsif current_page?(searches_search_path)%>
                    <div class = "search_peko">
                      <h7>今の腹ペコ度でお店の絞込みできます。</h7>
                      <div class = "form-select">
                        <%= form_with url: searches_search_path, method: :get, local: true do |f| %>
                          <%= f.select :peko, [['ちょいペコ','ちょいペコ'], ['ペコ','ペコ'], ['ペコMAX','ペコMAX']], {prompt: '  --  選択してください  --  '}, class: "select" %>
                          <div class = "submit" ><%= f.submit '検索' %></div>
                        <% end %>
                      </div>
                  　</div>
                  <% end %>
              <ul class="channel_list text-center">
               <% if admin_signed_in? %>
                  <li class="nav-item nav-link"><h4><%= link_to "会員一覧", admin_users_path, class:"link" %></h4></li>
                  <li class="nav-item nav-link"><h4><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"link" %></h4></h4></li>
                <% elsif user_signed_in? %>
                  <li class="nav-item nav-link">
                    <%= link_to maps_path, class:"link" do %><i class="fas fa-utensils fa-5x"></i><div><strong>投稿一覧</strong></div>
                    <% end %>
                  </li>
                  <li class="nav-item nav-link">
                    <%= link_to new_map_path, class:"link" do %><i class="fas fa-map-marked-alt fa-5x"></i><div><strong>投稿する</strong></div>
                    <% end %>
                  </li>
                  <li class="nav-item nav-link">
                    <%= link_to user_path(current_user.id), class:"link" do %><i class="fas fa-heart fa-5x"></i><div><strong>お気に入り</strong></div>
                    <% end %>
                  </li>
                  <li class="nav-item nav-link">
                    <%= link_to destroy_user_session_path, method: :delete, class:"link" do %><i class="fas fa-sign-out-alt fa-5x"></i><div><strong>ログアウト</strong></div>
                    <% end %>
                  </li>
                <% else %>
                  <li class="nav-item nav-link"><%= link_to root_path, class:"link" do %>
                    <i class="fas fa-utensils fa-5x"></i><div><strong>投稿一覧</strong></div>
                    <% end %>
                  </li>
                  <li class="nav-item nav-link"><%= link_to home_about_path, class:"link" do %>
                    <i class="fas fa-book-reader fa-5x"></i><div><strong>当サイトについて</strong></div>
                    <% end %>
                  </li>
                  <li class="nav-item nav-link"><%= link_to new_user_registration_path, class:"link" do %>
                    <i class="fas fa-user-plus fa-5x"></i><div><strong>新規登録</strong></div>
                  <% end %>
                  </li>
                  <li class="nav-item nav-link"><%= link_to new_user_session_path, class:"link" do  %>
                    <i class="fas fa-sign-in-alt fa-5x"></i><div><strong>ログイン</strong></div>
                  <% end %>
                  </li>
               <% end %>
              </ul>
          </div>
        </div>
      </div>
     <%= yield %>
    </div>
  </body>
</html>